### ISSUE TITLE
Font render should generate a text object with a VBO and font texture.

### ISSUE THREAD

**Issue by archSeer** [polyfox/moon#11]
```ruby
font.generate(...) => Moon::Text(vbo, texture)
text.render
```

By caching the VBO, we skip tons of calculations per frame.

This will be possible once we finish fully extracting textures and vbos.

**Comment by IceDragon200** [comment]
:+1: 
Guess I better go rename the current `Moon::Text` to `Moon::Label`

**Comment by IceDragon200** [comment]
PR is here #15

**Comment by archSeer** [comment]
Closed by #15.
