### ISSUE TITLE
Default shaders should be compiled and embedded into the core.

### ISSUE THREAD

**Issue by archSeer** [polyfox/moon#20]
That way people don't have to manually copy them over. This is possible now that we are able to create shaders from strings.

**Comment by IceDragon200** [comment]
+1 It would mean less copying for me every time I want to make a test project

**Comment by archSeer** [comment]
I figure the best way is to generate a `.rb` file with those string constants, during the build process.

**Comment by archSeer** [comment]
@IceDragon200, you need to use "Closes #n" next time.
