### ISSUE TITLE
Remove Sprite, and Spritesheet Texture loading

### ISSUE THREAD

**Issue by IceDragon200** [polyfox/moon#27]
We should consider removing the `Sprite.new(filename)` and `Spritesheet.new(filename, cw, ch)` behavior.

Reason being, you may accidentally load the same texture multiple times (this is bad in the case of very large textures 2048+).

**Comment by archSeer** [comment]
Sounds good, agreed. We had a C++ cache, but that was too low-level. I think users controlling the caching is the best option.
