### ISSUE TITLE
mrb_field_write_barrier fails with Hash<Class, ThingWithA<Class>>

### ISSUE THREAD

**Issue by IceDragon200** [polyfox/moon#7]
This is here for safe keeping, until I can replicate the problem in mruby, without all of Moon's bells and whistles.

```
moon-mruby: /home/icy/docs/codes/polyfox/moon/vendor/mruby/src/gc.c:1138: mrb_field_write_barrier: Assertion `!(((value)->color & ((mrb)->current_white_part ^ (1 | (1 << 1))) & (1 | (1 << 1))) || (value)->tt == MRB_TT_FREE) && !(((obj)->color & ((mrb)->current_white_part ^ (1 | (1 << 1))) & (1 | (1 << 1))) || (obj)->tt == MRB_TT_FREE)' failed.
```

From what I've found, this problem was spawned by storing a Class in a Hash as a key, along with the Class appearing as a value in an Object.

aka:
```ruby
{
  Class => ThingThatStoresTheClass.new(Class)
}
```

Whats unexpected, is the Class is seen as `dead`, mark you, this Class is something that was globally defined, and not done via `Class.new`.
I thought classes were suppose to be industructable, but I guess I was wrong.

One final piece to the puzzle thus far is this only happens during load time via mruby-require.

I've temporarily alleviated the problem by disabling the GC before loading the game scripts and then re-enabling it after.

```ruby
GC.disable
require 'core/load'
require 'scripts/load'
GC.enable
```

This issue will be reported to the mruby team, ONLY and *ONLY* if it can be replicated in mruby itself without the bells and whistles of Moon (I believe I said that before..).

**Comment by archSeer** [comment]
@IceDragon200 might be worth testing if this is still an issue, a few things landed on mruby master.

**Comment by IceDragon200** [comment]
@archSeer Seems to be fine now, I'll close the issue, unless it shows up again.
Though, I'll leave in GC toggle in the bootstrap for now.
